name: Update Database
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 

      - name: Update Database
        run: ./update_benchmarks ${{ secrets.BM_API_KEY }} benchmarks.js

      - name: Publish changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Updated database'
          default_author: github_actions
