name: Update Database
on:
  schedule:
    - cron: '* 0 * * *'
  push:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 

      - name: Update Database
        run: python3 update_benchmarks.py ${{ secrets.AT_BASE_ID }} ${{ secrets.AT_API_KEY }} benchmarks.js
